spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_routes
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: test_routes2
          uri: htpps://www.qq.com
          predicates:  #????  ???????????uri
            - Query=url,qq
server:
  port: 88